ayb/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('_debug_/',include('debug_toolbar.urls')),
    path('',include('costos.urls'))
]

costos/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
      path('',views.index),
      path('forgot-password/', views.forgot_password, name="forgot-password"),
      path('buttons/', views.buttons, name="buttons"),
      path('register/', views.register, name="register"),
      path('login/', views.login, name="login"),
      path('dashboard/', views.dashboard, name="dashboard"),
      path('company/', views.CompanyListView.as_view(), name="CompanyListView"),
      path('company/<int:pk>/', views.company_detail, name="company_detail"),
      path('company/add/', views.company_create, name="add_company"),
      path('provider/', views.ProviderListView.as_view(), name="ProviderListView"),
      path('provider/<int:pk>/', views.provider_detail, name="provider_detail"),
      path('provider/add/', views.provider_create, name="add_provider"),
      path('restaurant/', views.RestaurantListView.as_view() , name="restaurant"),
      path('restaurant/<int:pk>/', views.restaurant_detail, name="restaurant_detail"),
      path('restaurant/add/', views.restaurant_create, name="add_restaurant"),
      path('receta/', views.RecetaListView.as_view() , name="receta"),
      path('receta/<int:pk>/', views.receta_detail, name="receta_detail"),
      path('receta/add/', views.receta_create, name="add_receta"),
      path('ingredient/', views.IngredientListView.as_view(), name="IngredientListView"),
      path('ingredient/<int:pk>/', views.ingredient_detail, name="ingredient_detail"),
      path('ingredient/add/', views.ingredient_create, name="ingredient_create"),

]

costos/models.py
from typing import Tuple
from django.db import models
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from simple_history.models import HistoricalRecords
from django.utils.translation import gettext_lazy as _
import pgtrigger

LANGUAGES = (
    ('en', _('English')),
    ('es', _('Spanish')),
)

User = get_user_model()

class Company(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(_('name'), max_length=250)
    description = models.CharField(_('description'), max_length=250, blank=True)
    address = models.CharField(_('address'), max_length=100, blank=True)
    city = models.CharField(_('city'),max_length=100, blank=True)
    state = models.CharField(_('state'),max_length=100, blank=True)
    zipCode = models.CharField(_('zipCode'),max_length=100, blank=True)
    contacto = models.CharField(_('contacto'),max_length=100, blank=True)
    notes = models.CharField(_('notes'),max_length=250, blank=True)
    email = models.EmailField(_('email'),max_length=70,blank=True)
    phone = models.CharField(_('phone'),max_length=250, blank=True)
    url_corp = models.CharField(_('url'),max_length=250, blank=True)
    feeds = models.CharField(_('feeds'),max_length=250, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('Company:detail', kwargs={
            'id':self.id
        })


class Provider(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(_('name'),max_length=250)
    description = models.CharField(_('description'),max_length=250, blank=True)
    address = models.CharField(_('address'),max_length=100, blank=True)
    city = models.CharField(_('city'),max_length=100, blank=True)
    state = models.CharField(_('state'),max_length=100, blank=True)
    zipcode = models.CharField(_('zipcode'),max_length=100, blank=True)
    contacto = models.CharField(_('contacto'),max_length=100, blank=True)
    notes = models.CharField(_('notes'),max_length=250, blank=True)
    email= models.EmailField(max_length=70,blank=True,unique=True)
    phone = models.CharField(_('phone'),max_length=250, blank=True)
    url_corp = models.CharField(_('url'),max_length=250, blank=True)
    feeds = models.CharField(_('feeds'),max_length=250, blank=True)
    company = models.ForeignKey(Company, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('Provider:detail', kwargs={
            'id': self.id
        })


class Restaurant(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(_('name'),max_length=250)
    description = models.CharField(_('description'),max_length=250, blank=True)
    address = models.CharField(_('address'),max_length=250, blank=True)
    city = models.CharField(_('city'),max_length=100, blank=True)
    state = models.CharField(_('state'),max_length=100, blank=True)
    zipCode = models.CharField(_('zipCode'),max_length=100, blank=True)
    contacto = models.CharField(_('contacto'),max_length=100, blank=True)
    notes = models.CharField(_('notes'),max_length=250, blank=True)
    email = models.EmailField(_('email'),max_length=70, blank=True)
    phone = models.CharField(_('phone'),max_length=250, blank=True)
    url_corp = models.CharField(_('url'),max_length=250, blank=True)
    feeds = models.CharField(_('feeds'),max_length=250, blank=True)
    chefs = models.ForeignKey(User, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, null=True, on_delete=models.SET_NULL)
    providers = models.ManyToManyField(Provider)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('Restaurant:detail', kwargs={
            'id': self.id
        })



class Ingredient(models.Model):

    GRAM = "gram"
    UNIT = "unit"
    MILLILITER = "milliliter"
    KILOGRAM = "kilogram"

    PRESENTATION_CHOICES = [
        (GRAM, "Gram"),
        (UNIT, "Unit"),
        (MILLILITER, "Milliliter"),
        (KILOGRAM, "Kilogram")
    ]

    GROCERY = "grocery"
    PROTEIN = "protein"
    FRUVER = "fruVer"
    CATEGORY_CHOICES = [
        (GROCERY, "Grocery"),
        (PROTEIN, "Protein"),
        (FRUVER, "FruVer")
    ]

    id = models.AutoField(primary_key=True)
    name = models.CharField(_('name'),max_length=250)
    type = models.CharField(_('type'),max_length=50,choices=CATEGORY_CHOICES, default=GROCERY)
    presentation = models.CharField(_('presentation'),max_length=50,choices=PRESENTATION_CHOICES, default=GRAM)
    created_on = models.DateTimeField(auto_now_add=True)
    description = models.TextField(_('description'),max_length=999)
    price = models.DecimalField(max_digits=20, decimal_places=10)
    qty = models.DecimalField(max_digits=20, decimal_places=10)
    provider = models.ForeignKey(Provider,null=True, on_delete=models.SET_NULL)
    chef = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    merma = models.DecimalField(max_digits=10,decimal_places=6, default=0.1)
    history = HistoricalRecords()


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('Ingredient:detail', kwargs={
            'id': self.id
        })


class Receta(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(_('name'),max_length=100)
    description = models.CharField(_('description'),max_length=250,blank=True)
    isComplete = models.BooleanField(default=False)
    cost = models.DecimalField(max_digits=20, decimal_places=10)
    portions = models.DecimalField(max_digits=20, decimal_places=10, default=1.0)
    mpcost = models.DecimalField(max_digits=20, decimal_places=10,blank=True)
    prepacost = models.DecimalField(max_digits=20, decimal_places=10,blank=True)
    portioncost = models.DecimalField(max_digits=20, decimal_places=10,blank=True)
    mpestablish = models.DecimalField(max_digits=20, decimal_places=10,blank=True)
    errormargin = models.DecimalField(max_digits=20, decimal_places=10,blank=True)
    realratemp  = models.DecimalField(max_digits=20, decimal_places=10,blank=True)
    saleprice = models.DecimalField(max_digits=20, decimal_places=10,blank=True)
    menuprice = models.DecimalField(max_digits=20, decimal_places=10,blank=True)
    realsaleprice = models.DecimalField(max_digits=20, decimal_places=10,blank=True)
    taxportion = models.DecimalField(max_digits=20, decimal_places=10,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now= True)
    restaurant = models.ForeignKey(Restaurant, null=True, on_delete=models.SET_NULL)
    items = models.ManyToManyField(Ingredient,through='Steps',through_fields=('receta','ingredient'))
    chef = models.ForeignKey(User,null=True, on_delete=models.SET_NULL)
    history = HistoricalRecords()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('Receta:detail', kwargs={
            'id': self.id
        })


class Steps(models.Model):
   id = models.AutoField(primary_key=True)
   receta = models.ForeignKey(Receta,on_delete=models.CASCADE)
   ingredient = models.ForeignKey(Ingredient,on_delete=models.CASCADE)
   qty = models.DecimalField(max_digits=20,decimal_places=10)
   preparacion = models.CharField(max_length=250)
   merma = models.DecimalField(max_digits=10,decimal_places=6)


   def __str__(self):
        return self.preparacion

   def get_absolute_url(self):
        return reverse('Step:detail', kwargs={
            'id': self.id
        })

costos/forms.py
from django import forms
from .models import Company
from .models import Restaurant
from .models import Provider
from .models import Ingredient
from .models import Receta
from .models import Steps


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = [
            'name',
            'description',
            'address',
            'city',
            'state',
            'contacto',
            'notes',
            'email',
            'url_corp',
            'feeds'
        ]


class ProviderForm(forms.ModelForm):
    class Meta:
        model = Provider
        fields = [
            'name',
            'description',
            'address',
            'city',
            'state',
            'zipcode',
            'contacto',
            'notes',
            'email',
            'url_corp',
            'feeds',
            'TINid'

        ]



class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = [
            'name',
            'description',
            'address',
            'city',
            'state',
            'contacto',
            'notes',
            'email',
            'url_corp',
            'feeds',
            'company',
            'providers',
            'chefs'
        ]


class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = [
            'provider',
            'name',
            'description',
            'presentation',
            'type',
            'price',
            'qty',
            'merma'

        ]

class RecetaForm(forms.ModelForm):

    class Meta:
        model = Receta
        fields = [
            'chef',
            'restaurant',
            'name',
            'description',
            'portions',
            'items',
            'mpcost',
            'prepacost',
            'portioncost',
            'mpestablish',
            'errormargin',
            'realratemp',
            'saleprice',
            'menuprice',
            'realsaleprice',
            'taxportion'

        ]



class StepsForm(forms.ModelForm):
    class Meta:
        model = Steps
        fields = [
            'preparacion',
            'merma',
            'qty'

        ]

costos/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic.list import ListView
from .models import Ingredient
from .models import Company
from .models import Restaurant
from .models import Provider
from .models import Receta
from .forms import RecetaForm
from .forms import IngredientForm
from .forms import CompanyForm
from .forms import ProviderForm
from .forms import RestaurantForm
from .forms import StepsForm
from django.http import HttpResponse


def index(request):
    return render(request, 'costos/index.html')

def dashboard(request):
    return render(request, 'costos/dashboard.html')


def company_create(request):
    form = CompanyForm(request.POST or None)
    if form.is_valid():
        form.save()
    context = {
        'form': form
    }
    return render(request, "costos/company_create.html",
    context)

def company(request):
   return render(request, 'costos/company.html')

class CompanyListView(ListView):
   model = Company

def company_detail(request, pk):
    company = Company.objects.get(pk=pk)

    if request.method == 'POST':
        Provider.save()

        return redirect('provider_list')
    return render(request, 'costos/company_detail.html', {'company': company})

def provider(request):
   return render(request, 'costos/provider.html')

class ProviderListView(ListView):
   model = Provider

def provider_detail(request, pk):
    provider = Provider.objects.get(pk=pk)

    if request.method == 'POST':
        Provider.save()

        return redirect('provider_list')

    return render(request, 'costos/provider_detail.html', {'provider': provider})


def provider_create(request):
    form = IngredientForm(request.POST or None)
    if form.is_valid():
        form.save()
    context = {
        'form': form
    }
    return render(request, "costos/provider_create.html",
    context)


def restaurant(request):
   return render(request, 'costos/restaurant.html')

class RestaurantListView(ListView):
   model = Restaurant

def restaurant_detail(request, pk):
    restaurant = Restaurant.objects.get(pk=pk)

    if request.method == 'POST':
        Restaurant.save()

        return redirect('provider_list')

    return render(request, 'costos/restaurant_detail.html', {'restaurant': restaurant})


def restaurant_create(request):
    form = RestaurantForm(request.POST or None)
    if form.is_valid():
        form.save()
    context = {
        'form': form
    }
    return render(request, "costos/restaurant_create.html",
    context)


def ingredient_create(request):
    form = IngredientForm(request.POST or None)
    if form.is_valid():
        form.save()
    context = {
        'form': form
    }
    return render(request, "costos/ingredient_create.html",
    context)

class IngredientListView(ListView):
   model = Ingredient


def ingredient_detail(request, pk):
    ingredient = Ingredient.objects.get(pk=pk)

    if request.method == 'POST':
        Ingredient.save()

        return redirect('ingredient_list')

    return render(request, 'costos/ingredient_detail.html', {'ingredient': ingredient})

class RecetaListView(ListView):
   model = Receta

def receta(request):
   return render(request, 'costos/receta.html')


def receta_create(request):
    form = RecetaForm(request.POST or None)
    if form.is_valid():
        form.save()
    context = {
        'form': form
    }
    return render(request, "costos/receta_create.html",
    context)


def receta_detail(request, pk):
    receta = Receta.objects.get(pk=pk)

    if request.method == 'POST':
        Receta.save()

        return redirect('recetalist')

    return render(request, 'costos/restaurant_detail.html', {'restaurant': restaurant})


def login(request):
   return render(request, 'costos/login.html')


def register(request):
   return render(request, 'costos/register.html')


def forgot_password(request):
   return render(request, 'costos/forgot-password.html')


def buttons(request):
   return render(request, 'costos/buttons.html')

templates/costos/company.html
{% extends 'costos/minBase.html' %}
{% load i18n %}
{%load static %}
{% block meta_desc %} A&B Cost {% endblock %}
{% block title %} A&B Cost - Company {% endblock %}
{%block content %}
   <p>This is Company</p>
 <object>This <id> {{id}}</id></object>
{% endblock %}}

templates/costos/company_list.html
{% extends 'costos/minBase.html' %}
{% load i18n %}
{%load static %}
{% block meta_desc %} A&B Cost {% endblock %}
{% block title %} A&B Cost - Companies {% endblock %}
{%block content %}
<h2>All Companies </h2>
  <div class="row">
	  {% for object in object_list %}
   <div class="col-xl-3 col-md-6 mb-4">
  		<div class="card border-left-primary shadow h-100 py-2">
			<div class="card-body">
				<div class="row no-gutters align-items-center">
					<div class="col mr-2">
						<div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
						{{object.description}}</div>
						<div class="h5 mb-0 font-weight-bold text-gray-800">{{ object.name }} {{ object.description }}</div>
                       </div>
                   </div>
			</div>
           </div>
   </div>
{% endfor %}
 </div>

{% endblock %}}

templates/costos/forgot-password.html
{% extends 'costos/minBase.html' %}
{% load i18n %}
{%load static %}
{% block meta_desc %} A&B Cost {% endblock %}
{% block title %} A&B Cost - Forgot Password<{% endblock %}
{%block content %}
 <body class="bg-gradient-primary">
    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                                        <p class="mb-4">We get it, stuff happens. Just enter your email address below
                                            and we'll send you a link to reset your password!</p>
                                    </div>
                                    <form class="user">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Enter Email Address...">
                                        </div>
                                        <a href="login.html" class="btn btn-primary btn-user btn-block">
                                            Reset Password
                                        </a>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="register.html">Create an Account!</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="login.html">Already have an account? Login!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

{% endblock %}}

templates/costos/ingredient_create.html
{% extends 'costos/minBase.html' %}
{% load i18n %}
{%load static %}
{% block meta_desc %} A&B Cost {% endblock %}
{% block title %} A&B Cost - Ingredient {% endblock %}
{%block content %}
 <div class="text-center">
   <h1 class="h4 text-gray-900 mb-4">Add Ingredient</h1>
 </div>
 <body class="bg-gradient-primary">
  <div class="container">
   <div class="row justify-content-center">
     <div class="col-xl-10 col-lg-12 col-md-9">
         <div class="card o-hidden border-0 shadow-lg my-5">
             <div class="card-body p-3">
                <div class="form-group">
                 <form method="post">
    {% csrf_token %}
    <p>
    <label for="id_provider">Provider:</label>
    <select name="provider" class="form-control form-control-user"  required id="id_provider">
      <option value="" selected>---------</option>
        <option value="1">Exito</option>

    </select>

  </p>
  <p>
    <label for="id_name">Name:</label>
    <input type="text" name="name" class="form-control form-control-user" maxlength="250" required id="id_name">
  </p>
  <p>
    <label for="id_description">Description:</label>
    <textarea name="description" class="form-control form-control-user" cols="40" rows="10" maxlength="999" required id="id_description">
    </textarea>
  </p>
  <p>
    <label for="id_presentation">Presentation:</label>
    <select name="presentation" class="form-control form-control-user"  id="id_presentation">
    <option value="gram" selected>Gram</option>
      <option value="unit">Unit</option>
      <option value="milliliter">Milliliter</option>
      <option value="kilogram">Kilogram</option>
    </select>
  </p>
  <p>
    <label for="id_type">Type:</label>
    <select name="type" class="form-control form-control-user"  id="id_type">
    <option value="grocery" selected>Grocery</option>
      <option value="protein">Protein</option>
      <option value="fruVer">FruVer</option>
    </select>
  </p>
  <p>
    <label for="id_price">Price:</label>
    <input type="number" class="form-control form-control-user" name="price" step="1e-10" required id="id_price">
  </p>
  <p>
    <label for="id_qty">Qty:</label>
    <input type="number" class="form-control form-control-user" name="qty" step="1e-10" required id="id_qty">
  </p>
  <p>
    <label for="id_merma">Merma:</label>
    <input type="number" class="form-control form-control-user" name="merma" value="0.1" step="0.000001" required id="id_merma">
  </p>
     <input type='submit' class="btn btn-primary btn-user btn-block"  value='Save'/>
 </form>

      </div>

            </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

{% endblock %}}

templates/costos/provider.html
{% extends 'costos/minBase.html' %}
{% load i18n %}
{%load static %}
{% block meta_desc %} A&B Cost {% endblock %}
{% block title %} A&B Cost - Ingrediente {% endblock %}
{%block content %}
   <p>This is Provider</p>
 <object>This <id> {{id}}</id></object>
{% endblock %}}

templates/costos/provider_list.html
{% extends 'costos/minBase.html' %}
{% load i18n %}
{%load static %}
{% block meta_desc %} A&B Cost {% endblock %}
{% block title %} A&B Cost - Provider {% endblock %}
{%block content %}
<h2>All Provider </h2>
  <div class="row">
	  {% for object in object_list %}
   <div class="col-xl-3 col-md-6 mb-4">
  		<div class="card border-left-primary shadow h-100 py-2">
			<div class="card-body">
				<div class="row no-gutters align-items-center">
					<div class="col mr-2">
						<div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
						{{object.name}}</div>
						<div class="h5 mb-0 font-weight-bold text-gray-800">{{ object.id }} {{ object.address }}</div>
                       </div>
                   </div>
			</div>
           </div>
   </div>
{% endfor %}
 </div>

{% endblock %}}

templates/costos/receta.html
{% extends 'costos/minBase.html' %}
{% load i18n %}
{%load static %}
{% block meta_desc %} Alimentos & Bebidas - Analisis de Costos {% endblock %}
{% block title %} A&B Cost - Receta {% endblock %}
{%block content %}
   <p>This is Receta</p>
{% endblock %}}

templates/costos/register.html
{% extends 'costos/minBase.html' %}
{% load i18n %}
{%load static %}
{% block meta_desc %} A&B Cost {% endblock %}
{% block title %} A&B Cost - Register {% endblock %}
{%block content %}
<body class="bg-gradient-primary">

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                            </div>
                            <form class="user">
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="text" class="form-control form-control-user" id="exampleFirstName"
                                            placeholder="First Name">
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="text" class="form-control form-control-user" id="exampleLastName"
                                            placeholder="Last Name">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="email" class="form-control form-control-user" id="exampleInputEmail"
                                        placeholder="Email Address">
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="password" class="form-control form-control-user"
                                            id="exampleInputPassword" placeholder="Password">
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="password" class="form-control form-control-user"
                                            id="exampleRepeatPassword" placeholder="Repeat Password">
                                    </div>
                                </div>
                                <a href="login.html" class="btn btn-primary btn-user btn-block">
                                    Register Account
                                </a>

                            </form>
                            <hr>
                            <div class="text-center">
                                <a class="small" href="forgot-password.html">Forgot Password?</a>
                            </div>
                            <div class="text-center">
                                <a class="small" href="login.html">Already have an account? Login!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

{% endblock %}}

templates/costos/restaurant.html
{% extends 'costos/minBase.html' %}
{% load i18n %}
{%load static %}
{% block meta_desc %} A&B Cost {% endblock %}
{% block title %} A&B Cost - Ingrediente {% endblock %}
{%block content %}
   <p>This is Restaurant</p>
 <object>This <id> {{id}}</id></object>
{% endblock %}}

templates/costos/restaurant_create.html
{% extends 'costos/minBase.html' %}
{% load i18n %}
{%load static %}
{% block meta_desc %} A&B Cost {% endblock %}
{% block title %} A&B Cost - Create Restaurant {% endblock %}
{%block content %}
<h1>Add Restaurant</h1>
<form method="post">{% csrf_token %}
     <p>
    <label for="id_name">Name:</label>
    <input type="text" name="name" maxlength="250" required id="id_name">
  </p>
  <p>
    <label for="id_description">Description:</label>
    <input type="text" name="description" maxlength="250" id="id_description">
  </p>
  <p>
    <label for="id_address">Address:</label>
    <input type="text" name="address" maxlength="250" id="id_address">
  </p>
  <p>
    <label for="id_city">City:</label>
    <input type="text" name="city" maxlength="100" id="id_city">
  </p>
  <p>
    <label for="id_state">State:</label>
    <input type="text" name="state" maxlength="100" id="id_state">
  </p>
  <p>
    <label for="id_contacto">Contacto:</label>
    <input type="text" name="contacto" maxlength="100" id="id_contacto">
  </p>
  <p>
    <label for="id_notes">Notes:</label>
    <input type="text" name="notes" maxlength="250" id="id_notes">
  </p>
  <p>
    <label for="id_email">Email:</label>
    <input type="email" name="email" maxlength="70" id="id_email">
  </p>
  <p>
    <label for="id_url_corp">Url:</label>
    <input type="text" name="url_corp" maxlength="250" id="id_url_corp">
  </p>
  <p>
    <label for="id_feeds">Feeds:</label>
    <input type="text" name="feeds" maxlength="250" id="id_feeds">
  </p>
  <p>
    <label for="id_company">Company:</label>
    <select name="company" required id="id_company">
  <option value="" selected>---------</option>
  <option value="1">NS Corporation</option>
</select>
  </p>
  <p>
    <label for="id_providers">Providers:</label>
    <select name="providers" required id="id_providers" multiple>
  <option value="1">Exito</option>
</select>
  </p>
  <p>
    <label for="id_chefs">Chefs:</label>
    <select name="chefs" required id="id_chefs">
  <option value="" selected>---------</option>
  <option value="2">gloria</option>
  <option value="1">nscguser</option>
</select>
  </p>
     <input type='submit' value='Save'/>
 </form>


{% endblock %}}

templates/costos/restaurant_list.html
{% extends 'costos/minBase.html' %}
{% load i18n %}
{%load static %}
{% block meta_desc %} A&B Cost {% endblock %}
{% block title %} A&B Cost - Ingredientes {% endblock %}
{%block content %}
<h2>All Resturant </h2>
  <div class="row">
	  {% for object in object_list %}
   <div class="col-xl-3 col-md-6 mb-4">
  		<div class="card border-left-primary shadow h-100 py-2">
			<div class="card-body">
				<div class="row no-gutters align-items-center">
					<div class="col mr-2">
						<div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
						{{object.description}}</div>
						<div class="h5 mb-0 font-weight-bold text-gray-800">{{ object.name }} {{ object.description }}</div>
                       </div>
                   </div>
			</div>
           </div>
   </div>
{% endfor %}
 </div>

{% endblock %}}